# fly.toml app configuration file generated for tsoha-pelikauppa on 2024-04-04T23:18:15+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tsoha-pelikauppa'
primary_region = 'arn'

[build]

[env]
  on_fly = "x"
  PORT ="5000"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
